"use client";

import React, { useState, useEffect, useRef } from "react";
import { useParams, useLocation, useNavigate } from "react-router-dom";
import { 
  Mic, MicOff, Video, VideoOff, PhoneOff, 
  MessageSquare, FileText, Send, X, 
  Maximize2, Settings, User, Download, ShoppingCart,
  ShieldCheck, Info
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { toast } from "sonner";

const VideoCall = () => {
  const { appointmentId } = useParams();
  const location = useLocation();
  const navigate = useNavigate();
  const doctor = location.state?.doctor || { 
    name: "Dr. Sarah Johnson", 
    specialty: "General Physician", 
    photoUrl: "https://images.unsplash.com/photo-1559839734-2b71f1536780?auto=format&fit=crop&q=80&w=200&h=200" 
  };

  const [isMuted, setIsMuted] = useState(false);
  const [isVideoOff, setIsVideoOff] = useState(false);
  const [showChat, setShowChat] = useState(false);
  const [messages, setMessages] = useState([
    { id: 1, sender: "doctor", text: "Hello! I'm Dr. Johnson. How can I help you today?", time: "10:00 AM" }
  ]);
  const [newMessage, setNewMessage] = useState("");
  const [callDuration, setCallDuration] = useState(0);
  const [showPrescription, setShowPrescription] = useState(false);
  
  const userVideoRef = useRef<HTMLVideoElement>(null);
  const [stream, setStream] = useState<MediaStream | null>(null);

  // Initialize User Camera
  useEffect(() => {
    async function setupCamera() {
      try {
        const userStream = await navigator.mediaDevices.getUserMedia({ 
          video: true, 
          audio: true 
        });
        setStream(userStream);
        if (userVideoRef.current) {
          userVideoRef.current.srcObject = userStream;
        }
      } catch (err) {
        console.error("Error accessing camera:", err);
        toast.error("Could not access camera. Please check permissions.");
      }
    }
    setupCamera();

    return () => {
      if (stream) {
        stream.getTracks().forEach(track => track.stop());
      }
    };
  }, []);

  // Call Timer
  useEffect(() => {
    const timer = setInterval(() => {
      setCallDuration(prev => prev + 1);
    }, 1000);
    return () => clearInterval(timer);
  }, []);

  const formatTime = (seconds: number) => {
    const mins = Math.floor(seconds / 60);
    const secs = seconds % 60;
    return `${mins.toString().padStart(2, '0')}:${secs.toString().padStart(2, '0')}`;
  };

  const handleSendMessage = (e: React.FormEvent) => {
    e.preventDefault();
    if (!newMessage.trim()) return;
    
    const msg = {
      id: Date.now(),
      sender: "user",
      text: newMessage,
      time: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
    };
    
    setMessages([...messages, msg]);
    setNewMessage("");
    
    // Simulate doctor reply
    setTimeout(() => {
      if (newMessage.toLowerCase().includes("fever") || newMessage.toLowerCase().includes("headache")) {
        setMessages(prev => [...prev, {
          id: Date.now() + 1,
          sender: "doctor",
          text: "I understand. Based on your symptoms, I'll prescribe some medication and I'd like you to monitor your temperature.",
          time: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
        }]);
        
        setTimeout(() => {
          setShowPrescription(true);
          toast.success("E-Prescription generated by doctor!");
        }, 2000);
      }
    }, 1500);
  };

  const handleEndCall = () => {
    if (stream) {
      stream.getTracks().forEach(track => track.stop());
    }
    toast.info("Consultation ended.");
    navigate("/teleconsultation");
  };

  return (
    <div className="flex h-screen flex-col bg-slate-950 text-white overflow-hidden">
      {/* Header */}
      <header className="flex items-center justify-between px-6 py-4 bg-slate-900/80 backdrop-blur-md border-b border-white/10 z-30">
        <div className="flex items-center gap-4">
          <div className="h-10 w-10 rounded-full overflow-hidden border border-primary/50">
            <img src={doctor.photoUrl} className="h-full w-full object-cover" />
          </div>
          <div>
            <div className="flex items-center gap-2">
              <h2 className="font-bold text-sm">{doctor.name}</h2>
              <Badge variant="outline" className="h-4 px-1 text-[8px] border-success/50 text-success bg-success/5">
                LIVE
              </Badge>
            </div>
            <p className="text-[10px] text-slate-400 uppercase tracking-wider">{doctor.specialty}</p>
          </div>
          <Badge variant="outline" className="ml-4 border-primary/30 text-primary bg-primary/5 font-mono">
            {formatTime(callDuration)}
          </Badge>
        </div>
        
        <div className="flex items-center gap-4">
          <div className="hidden md:flex items-center gap-2 text-[10px] text-slate-400">
            <ShieldCheck className="h-3 w-3 text-success" />
            End-to-End Encrypted
          </div>
          <div className="flex items-center gap-2">
            <Button variant="ghost" size="icon" className="text-slate-400 hover:text-white">
              <Settings className="h-5 w-5" />
            </Button>
            <Button variant="ghost" size="icon" className="text-slate-400 hover:text-white">
              <Maximize2 className="h-5 w-5" />
            </Button>
          </div>
        </div>
      </header>

      {/* Main Content */}
      <div className="flex flex-1 relative overflow-hidden">
        {/* Video Area */}
        <div className="flex-1 relative bg-slate-900 flex items-center justify-center">
          {/* Doctor Video (Main) */}
          <div className="absolute inset-0 flex items-center justify-center overflow-hidden">
            {/* Realistic Doctor Consultation Video */}
            <video 
              autoPlay 
              loop 
              muted 
              playsInline
              className="h-full w-full object-cover opacity-90"
            >
              <source src="https://assets.mixkit.co/videos/preview/mixkit-female-doctor-talking-to-a-patient-on-a-video-call-41259-large.mp4" type="video/mp4" />
              Your browser does not support the video tag.
            </video>
            <div className="absolute inset-0 bg-gradient-to-t from-slate-950/80 via-transparent to-slate-950/20" />
          </div>

          {/* User Video (PIP) */}
          <div className="absolute top-6 right-6 w-48 h-32 md:w-64 md:h-40 rounded-2xl overflow-hidden border-2 border-white/20 shadow-2xl bg-slate-800 z-20 group transition-all hover:scale-105">
            {isVideoOff ? (
              <div className="h-full w-full flex flex-col items-center justify-center bg-slate-800">
                <User className="h-12 w-12 text-slate-600 mb-2" />
                <p className="text-[10px] text-slate-500">Camera Off</p>
              </div>
            ) : (
              <video 
                ref={userVideoRef} 
                autoPlay 
                muted 
                playsInline 
                className="h-full w-full object-cover mirror"
              />
            )}
            <div className="absolute bottom-3 left-3 flex items-center gap-2">
              <Badge className="bg-black/60 backdrop-blur-md text-[10px] px-2 py-0.5 border border-white/10">You</Badge>
              {isMuted && <MicOff className="h-3 w-3 text-destructive" />}
            </div>
          </div>

          {/* Controls Overlay */}
          <div className="absolute bottom-10 left-1/2 -translate-x-1/2 flex items-center gap-4 z-30">
            <div className="flex items-center gap-3 bg-slate-900/80 backdrop-blur-xl p-3 rounded-full border border-white/10 shadow-2xl">
              <Button 
                variant={isMuted ? "destructive" : "ghost"} 
                size="icon" 
                className={`h-12 w-12 rounded-full transition-all ${!isMuted ? 'hover:bg-white/10' : ''}`}
                onClick={() => setIsMuted(!isMuted)}
              >
                {isMuted ? <MicOff className="h-5 w-5" /> : <Mic className="h-5 w-5" />}
              </Button>
              
              <Button 
                variant={isVideoOff ? "destructive" : "ghost"} 
                size="icon" 
                className={`h-12 w-12 rounded-full transition-all ${!isVideoOff ? 'hover:bg-white/10' : ''}`}
                onClick={() => setIsVideoOff(!isVideoOff)}
              >
                {isVideoOff ? <VideoOff className="h-5 w-5" /> : <Video className="h-5 w-5" />}
              </Button>

              <div className="w-px h-8 bg-white/10 mx-1" />

              <Button 
                variant="destructive" 
                size="icon" 
                className="h-14 w-14 rounded-full shadow-xl hover:scale-110 transition-transform active:scale-95"
                onClick={handleEndCall}
              >
                <PhoneOff className="h-6 w-6" />
              </Button>

              <div className="w-px h-8 bg-white/10 mx-1" />

              <Button 
                variant={showChat ? "default" : "ghost"} 
                size="icon" 
                className={`h-12 w-12 rounded-full transition-all ${showChat ? 'bg-primary hover:bg-primary/90' : 'hover:bg-white/10'}`}
                onClick={() => {
                  setShowChat(!showChat);
                  if (showPrescription) setShowPrescription(false);
                }}
              >
                <MessageSquare className="h-5 w-5" />
              </Button>

              <Button 
                variant={showPrescription ? "default" : "ghost"} 
                size="icon" 
                className={`h-12 w-12 rounded-full transition-all ${showPrescription ? 'bg-primary hover:bg-primary/90' : 'hover:bg-white/10'}`}
                onClick={() => {
                  setShowPrescription(!showPrescription);
                  if (showChat) setShowChat(false);
                }}
              >
                <FileText className="h-5 w-5" />
              </Button>
            </div>
          </div>

          {/* Connection Status */}
          <div className="absolute top-6 left-6 z-20">
            <div className="flex items-center gap-2 bg-black/40 backdrop-blur-md px-3 py-1.5 rounded-full border border-white/10 text-[10px] font-medium">
              <div className="h-1.5 w-1.5 rounded-full bg-success animate-pulse" />
              Stable Connection
            </div>
          </div>
        </div>

        {/* Sidebar (Chat / Prescription) */}
        {(showChat || showPrescription) && (
          <div className="w-80 md:w-96 bg-slate-900 border-l border-white/10 flex flex-col animate-slide-in z-40">
            <div className="p-4 border-b border-white/10 flex items-center justify-between">
              <h3 className="font-bold text-sm flex items-center gap-2">
                {showChat ? <MessageSquare className="h-4 w-4 text-primary" /> : <FileText className="h-4 w-4 text-primary" />}
                {showChat ? "Consultation Chat" : "E-Prescription"}
              </h3>
              <Button variant="ghost" size="icon" className="h-8 w-8" onClick={() => { setShowChat(false); setShowPrescription(false); }}>
                <X className="h-4 w-4" />
              </Button>
            </div>

            <Tabs value={showPrescription ? "prescription" : "chat"} className="flex-1 flex flex-col">
              <TabsContent value="chat" className="flex-1 flex flex-col p-0 m-0">
                <ScrollArea className="flex-1 p-4">
                  <div className="space-y-4">
                    <div className="flex items-center gap-2 justify-center py-2">
                      <Badge variant="outline" className="text-[8px] border-white/10 text-slate-500 uppercase">
                        Consultation Started at {new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                      </Badge>
                    </div>
                    {messages.map(msg => (
                      <div key={msg.id} className={`flex flex-col ${msg.sender === 'user' ? 'items-end' : 'items-start'}`}>
                        <div className={`max-w-[85%] rounded-2xl px-4 py-2.5 text-sm shadow-sm ${
                          msg.sender === 'user' 
                            ? 'bg-primary text-white rounded-tr-none' 
                            : 'bg-slate-800 text-slate-200 rounded-tl-none border border-white/5'
                        }`}>
                          {msg.text}
                        </div>
                        <span className="text-[9px] text-slate-500 mt-1.5 px-1">{msg.time}</span>
                      </div>
                    ))}
                  </div>
                </ScrollArea>
                <form onSubmit={handleSendMessage} className="p-4 bg-slate-900/50 border-t border-white/10 flex gap-2">
                  <Input 
                    placeholder="Type a message..." 
                    className="bg-slate-800 border-white/5 text-white text-xs h-10 focus-visible:ring-primary"
                    value={newMessage}
                    onChange={(e) => setNewMessage(e.target.value)}
                  />
                  <Button type="submit" size="icon" className="h-10 w-10 shrink-0 hero-gradient shadow-lg">
                    <Send className="h-4 w-4" />
                  </Button>
                </form>
              </TabsContent>

              <TabsContent value="prescription" className="flex-1 p-4 m-0 overflow-y-auto">
                {showPrescription ? (
                  <div className="space-y-6 animate-fade-in">
                    <div className="rounded-2xl bg-white p-6 text-slate-900 shadow-2xl relative overflow-hidden">
                      <div className="absolute top-0 right-0 w-24 h-24 bg-primary/5 rounded-bl-full -mr-8 -mt-8" />
                      
                      <div className="flex justify-between items-start border-b border-slate-100 pb-4 mb-4">
                        <div>
                          <h3 className="font-bold text-sm text-primary">{doctor.name}</h3>
                          <p className="text-[9px] text-slate-500 font-bold uppercase tracking-tighter">{doctor.specialty}</p>
                          <p className="text-[8px] text-slate-400 mt-1">Reg No: MC-2024-8892</p>
                        </div>
                        <div className="text-right">
                          <p className="text-[9px] font-bold text-slate-400 uppercase">Date</p>
                          <p className="text-[10px] font-bold">{new Date().toLocaleDateString()}</p>
                        </div>
                      </div>
                      
                      <div className="space-y-4">
                        <div className="flex items-center gap-2">
                          <div className="h-6 w-6 rounded-lg bg-primary/10 flex items-center justify-center text-primary text-xs font-bold">Rx</div>
                          <p className="text-xs font-bold text-slate-700">Prescribed Medication</p>
                        </div>
                        
                        <div className="space-y-3">
                          <div className="p-3 rounded-xl bg-slate-50 border border-slate-100 group hover:border-primary/20 transition-colors">
                            <div className="flex justify-between items-start">
                              <p className="text-xs font-bold text-slate-800">Paracetamol 500mg</p>
                              <Badge className="text-[8px] h-4 bg-primary/10 text-primary border-none">Oral</Badge>
                            </div>
                            <p className="text-[10px] text-slate-500 mt-1 leading-relaxed">1 tablet twice daily after meals for 3 days.</p>
                          </div>
                          
                          <div className="p-3 rounded-xl bg-slate-50 border border-slate-100 group hover:border-primary/20 transition-colors">
                            <div className="flex justify-between items-start">
                              <p className="text-xs font-bold text-slate-800">Vitamin C 500mg</p>
                              <Badge className="text-[8px] h-4 bg-primary/10 text-primary border-none">Oral</Badge>
                            </div>
                            <p className="text-[10px] text-slate-500 mt-1 leading-relaxed">1 tablet daily for 10 days to boost immunity.</p>
                          </div>
                        </div>

                        <div className="pt-4 space-y-2">
                          <p className="text-[9px] font-bold text-slate-400 uppercase">Advice</p>
                          <p className="text-[10px] text-slate-600 italic leading-relaxed">
                            "Drink plenty of fluids and take complete bed rest for 48 hours. Monitor temperature every 6 hours."
                          </p>
                        </div>
                      </div>

                      <div className="mt-8 pt-4 border-t border-slate-100 flex justify-between items-end">
                        <div className="space-y-1">
                          <div className="h-10 w-10 bg-slate-50 rounded-lg border border-slate-100 flex items-center justify-center">
                            <ShieldCheck className="h-6 w-6 text-primary/20" />
                          </div>
                          <p className="text-[7px] text-slate-400">Verified Digital Signature</p>
                        </div>
                        <div className="text-right">
                          <div className="h-8 w-24 bg-slate-50 rounded border border-slate-100 mb-1 flex items-center justify-center">
                            <span className="font-heading italic text-xs text-primary/40">S. Johnson</span>
                          </div>
                          <p className="text-[8px] font-bold text-slate-500">Authorized Signatory</p>
                        </div>
                      </div>
                    </div>

                    <div className="grid grid-cols-2 gap-3">
                      <Button variant="outline" className="text-xs h-11 gap-2 border-white/10 bg-white/5 hover:bg-white/10">
                        <Download className="h-4 w-4" /> Download PDF
                      </Button>
                      <Button className="text-xs h-11 gap-2 hero-gradient shadow-lg" onClick={() => {
                        toast.success("Medicines added to cart!");
                        navigate("/medicines");
                      }}>
                        <ShoppingCart className="h-4 w-4" /> Order Now
                      </Button>
                    </div>
                    
                    <div className="p-4 rounded-xl bg-primary/5 border border-primary/10 flex gap-3">
                      <Info className="h-4 w-4 text-primary shrink-0" />
                      <p className="text-[10px] text-slate-400 leading-relaxed">
                        This e-prescription is valid for 30 days and can be used at any licensed pharmacy or ordered directly through MedCare.
                      </p>
                    </div>
                  </div>
                ) : (
                  <div className="flex flex-col items-center justify-center h-full text-center py-12 px-6">
                    <div className="h-16 w-16 rounded-full bg-slate-800 flex items-center justify-center mb-4">
                      <FileText className="h-8 w-8 text-slate-600" />
                    </div>
                    <h4 className="font-bold text-sm mb-2">No Prescription Yet</h4>
                    <p className="text-xs text-slate-500 leading-relaxed">
                      The doctor will generate an e-prescription during or after the consultation if required.
                    </p>
                  </div>
                )}
              </TabsContent>
            </Tabs>
          </div>
        )}
      </div>
      
      <style dangerouslySetInnerHTML={{ __html: `
        .mirror {
          transform: scaleX(-1);
        }
        @keyframes progress-loading {
          0% { transform: translateX(-100%); }
          100% { transform: translateX(100%); }
        }
        .animate-progress-loading {
          animation: progress-loading 2s infinite linear;
        }
      `}} />
    </div>
  );
};

export default VideoCall;