"use client";

import React, { useState, useEffect, useRef } from "react";
import { useParams, useLocation, useNavigate } from "react-router-dom";
import { 
  Mic, MicOff, Video, VideoOff, PhoneOff, 
  MessageSquare, FileText, Send, X, 
  Maximize2, Settings, User, Download, ShoppingCart,
  ShieldCheck, Activity
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { toast } from "sonner";

const VideoCall = () => {
  const { appointmentId } = useParams();
  const location = useLocation();
  const navigate = useNavigate();
  const doctor = location.state?.doctor || { 
    name: "Dr. Sarah Johnson", 
    specialty: "General Physician", 
    photoUrl: "https://images.unsplash.com/photo-1559839734-2b71f1536780?auto=format&fit=crop&q=80&w=200&h=200" 
  };

  const [isMuted, setIsMuted] = useState(false);
  const [isVideoOff, setIsVideoOff] = useState(false);
  const [showChat, setShowChat] = useState(false);
  const [messages, setMessages] = useState([
    { id: 1, sender: "doctor", text: "Hello! I'm Dr. Johnson. How can I help you today?", time: "10:00 AM" }
  ]);
  const [newMessage, setNewMessage] = useState("");
  const [callDuration, setCallDuration] = useState(0);
  const [showPrescription, setShowPrescription] = useState(false);
  
  const userVideoRef = useRef<HTMLVideoElement>(null);
  const [stream, setStream] = useState<MediaStream | null>(null);

  // Start user camera
  useEffect(() => {
    async function startCamera() {
      try {
        const mediaStream = await navigator.mediaDevices.getUserMedia({ 
          video: true, 
          audio: true 
        });
        setStream(mediaStream);
        if (userVideoRef.current) {
          userVideoRef.current.srcObject = mediaStream;
        }
      } catch (err) {
        console.error("Error accessing camera:", err);
        toast.error("Could not access camera. Please check permissions.");
      }
    }

    if (!isVideoOff) {
      startCamera();
    } else {
      if (stream) {
        stream.getTracks().forEach(track => track.stop());
        setStream(null);
      }
    }

    return () => {
      if (stream) {
        stream.getTracks().forEach(track => track.stop());
      }
    };
  }, [isVideoOff]);

  // Call timer
  useEffect(() => {
    const timer = setInterval(() => {
      setCallDuration(prev => prev + 1);
    }, 1000);
    return () => clearInterval(timer);
  }, []);

  const formatTime = (seconds: number) => {
    const mins = Math.floor(seconds / 60);
    const secs = seconds % 60;
    return `${mins.toString().padStart(2, '0')}:${secs.toString().padStart(2, '0')}`;
  };

  const handleSendMessage = (e: React.FormEvent) => {
    e.preventDefault();
    if (!newMessage.trim()) return;
    
    const msg = {
      id: Date.now(),
      sender: "user",
      text: newMessage,
      time: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
    };
    
    setMessages([...messages, msg]);
    setNewMessage("");
    
    // Simulate doctor reply
    setTimeout(() => {
      const lowerMsg = newMessage.toLowerCase();
      let reply = "I understand. Let me take a note of that.";
      
      if (lowerMsg.includes("fever") || lowerMsg.includes("headache")) {
        reply = "I see. I'll prepare a prescription for the symptoms. Please ensure you're getting enough rest.";
        setTimeout(() => {
          setShowPrescription(true);
          toast.success("E-Prescription generated by doctor!");
        }, 2000);
      } else if (lowerMsg.includes("hello") || lowerMsg.includes("hi")) {
        reply = "Hello! Please describe any symptoms or concerns you have.";
      }
      
      setMessages(prev => [...prev, {
        id: Date.now() + 1,
        sender: "doctor",
        text: reply,
        time: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
      }]);
    }, 1500);
  };

  const handleEndCall = () => {
    if (stream) {
      stream.getTracks().forEach(track => track.stop());
    }
    toast.info("Consultation ended.");
    navigate("/teleconsultation");
  };

  return (
    <div className="flex h-screen flex-col bg-slate-950 text-white overflow-hidden font-body">
      {/* Header */}
      <header className="flex items-center justify-between px-6 py-3 bg-slate-900/80 backdrop-blur-xl border-b border-white/5 z-30">
        <div className="flex items-center gap-4">
          <div className="relative">
            <div className="h-10 w-10 rounded-full overflow-hidden border-2 border-primary/50 shadow-lg shadow-primary/20">
              <img src={doctor.photoUrl} className="h-full w-full object-cover" alt={doctor.name} />
            </div>
            <div className="absolute -bottom-0.5 -right-0.5 h-3 w-3 rounded-full bg-success border-2 border-slate-900" />
          </div>
          <div>
            <div className="flex items-center gap-2">
              <h2 className="font-bold text-sm tracking-tight">{doctor.name}</h2>
              <Badge variant="outline" className="h-4 px-1.5 text-[8px] border-primary/30 text-primary bg-primary/5 uppercase font-bold">
                Specialist
              </Badge>
            </div>
            <p className="text-[10px] text-slate-400 uppercase tracking-widest font-medium">{doctor.specialty}</p>
          </div>
          <div className="ml-4 flex items-center gap-2 px-3 py-1 rounded-full bg-white/5 border border-white/10">
            <div className="h-1.5 w-1.5 rounded-full bg-destructive animate-pulse" />
            <span className="text-[10px] font-mono font-bold text-slate-300">{formatTime(callDuration)}</span>
          </div>
        </div>
        
        <div className="flex items-center gap-3">
          <div className="hidden sm:flex items-center gap-2 mr-4 px-3 py-1 rounded-lg bg-success/10 border border-success/20">
            <ShieldCheck className="h-3 w-3 text-success" />
            <span className="text-[10px] font-bold text-success uppercase">Encrypted</span>
          </div>
          <Button variant="ghost" size="icon" className="h-9 w-9 text-slate-400 hover:text-white hover:bg-white/10 rounded-xl">
            <Settings className="h-4 w-4" />
          </Button>
          <Button variant="ghost" size="icon" className="h-9 w-9 text-slate-400 hover:text-white hover:bg-white/10 rounded-xl">
            <Maximize2 className="h-4 w-4" />
          </Button>
        </div>
      </header>

      {/* Main Content */}
      <div className="flex flex-1 relative overflow-hidden">
        {/* Video Area */}
        <div className="flex-1 relative bg-slate-900 flex items-center justify-center overflow-hidden">
          {/* Doctor Video (Main) */}
          <div className="absolute inset-0 flex items-center justify-center bg-black">
            <video 
              autoPlay 
              loop 
              muted 
              playsInline
              className="h-full w-full object-cover opacity-90"
              poster={doctor.photoUrl}
            >
              <source src="https://player.vimeo.com/external/459389137.sd.mp4?s=916d03df35c867613a86163b0173f4016a3e2721&profile_id=164&oauth2_token_id=57447761" type="video/mp4" />
              Your browser does not support the video tag.
            </video>
            {/* Cinematic Overlays */}
            <div className="absolute inset-0 bg-gradient-to-t from-slate-950/80 via-transparent to-slate-950/40" />
            <div className="absolute inset-0 bg-primary/5 mix-blend-overlay" />
          </div>

          {/* User Video (PIP) */}
          <div className="absolute top-6 right-6 w-40 sm:w-56 aspect-video rounded-2xl overflow-hidden border-2 border-white/10 shadow-2xl bg-slate-800 z-20 group transition-all hover:scale-105">
            {isVideoOff ? (
              <div className="h-full w-full flex flex-col items-center justify-center bg-slate-800 gap-2">
                <div className="h-12 w-12 rounded-full bg-slate-700 flex items-center justify-center">
                  <User className="h-6 w-6 text-slate-500" />
                </div>
                <p className="text-[10px] font-bold text-slate-500 uppercase tracking-wider">Camera Off</p>
              </div>
            ) : (
              <video 
                ref={userVideoRef} 
                autoPlay 
                playsInline 
                muted 
                className="h-full w-full object-cover mirror"
              />
            )}
            <div className="absolute bottom-3 left-3 flex items-center gap-2">
              <Badge className="bg-black/60 backdrop-blur-md text-[9px] px-2 py-0.5 border-none font-bold">You</Badge>
              {!isMuted && <Activity className="h-3 w-3 text-primary animate-pulse" />}
            </div>
          </div>

          {/* Controls Overlay */}
          <div className="absolute bottom-10 left-1/2 -translate-x-1/2 flex items-center gap-4 z-30">
            <div className="flex items-center gap-3 px-6 py-3 rounded-3xl bg-slate-900/60 backdrop-blur-2xl border border-white/10 shadow-2xl">
              <Button 
                variant={isMuted ? "destructive" : "secondary"} 
                size="icon" 
                className={`h-12 w-12 rounded-2xl shadow-lg transition-all active:scale-95 ${!isMuted ? 'bg-white/10 hover:bg-white/20 border-white/10' : ''}`}
                onClick={() => setIsMuted(!isMuted)}
              >
                {isMuted ? <MicOff className="h-5 w-5" /> : <Mic className="h-5 w-5" />}
              </Button>
              
              <Button 
                variant={isVideoOff ? "destructive" : "secondary"} 
                size="icon" 
                className={`h-12 w-12 rounded-2xl shadow-lg transition-all active:scale-95 ${!isVideoOff ? 'bg-white/10 hover:bg-white/20 border-white/10' : ''}`}
                onClick={() => setIsVideoOff(!isVideoOff)}
              >
                {isVideoOff ? <VideoOff className="h-5 w-5" /> : <Video className="h-5 w-5" />}
              </Button>

              <div className="w-px h-8 bg-white/10 mx-1" />

              <Button 
                variant="destructive" 
                size="icon" 
                className="h-14 w-14 rounded-2xl shadow-xl shadow-destructive/20 animate-pulse-gentle hover:animate-none transition-all active:scale-95"
                onClick={handleEndCall}
              >
                <PhoneOff className="h-6 w-6" />
              </Button>

              <div className="w-px h-8 bg-white/10 mx-1" />

              <Button 
                variant={showChat ? "default" : "secondary"} 
                size="icon" 
                className={`h-12 w-12 rounded-2xl shadow-lg transition-all active:scale-95 ${showChat ? 'hero-gradient border-none' : 'bg-white/10 hover:bg-white/20 border-white/10'}`}
                onClick={() => {
                  setShowChat(!showChat);
                  if (showPrescription) setShowPrescription(false);
                }}
              >
                <MessageSquare className="h-5 w-5" />
              </Button>

              <Button 
                variant={showPrescription ? "default" : "secondary"} 
                size="icon" 
                className={`h-12 w-12 rounded-2xl shadow-lg transition-all active:scale-95 ${showPrescription ? 'hero-gradient border-none' : 'bg-white/10 hover:bg-white/20 border-white/10'}`}
                onClick={() => {
                  setShowPrescription(!showPrescription);
                  if (showChat) setShowChat(false);
                }}
              >
                <FileText className="h-5 w-5" />
              </Button>
            </div>
          </div>
        </div>

        {/* Sidebar (Chat / Prescription) */}
        {(showChat || showPrescription) && (
          <div className="w-80 sm:w-96 bg-slate-900/95 backdrop-blur-xl border-l border-white/10 flex flex-col animate-slide-in z-40">
            <div className="p-4 border-b border-white/5 flex items-center justify-between">
              <h3 className="font-bold text-sm uppercase tracking-widest text-slate-400">
                {showChat ? "Consultation Chat" : "Medical Records"}
              </h3>
              <Button variant="ghost" size="icon" className="h-8 w-8 rounded-lg" onClick={() => { setShowChat(false); setShowPrescription(false); }}>
                <X className="h-4 w-4" />
              </Button>
            </div>

            <Tabs value={showPrescription ? "prescription" : "chat"} className="flex-1 flex flex-col">
              <TabsContent value="chat" className="flex-1 flex flex-col p-0 m-0 overflow-hidden">
                <ScrollArea className="flex-1 p-6">
                  <div className="space-y-6">
                    {messages.map(msg => (
                      <div key={msg.id} className={`flex flex-col ${msg.sender === 'user' ? 'items-end' : 'items-start'}`}>
                        <div className={`max-w-[85%] rounded-2xl px-4 py-2.5 text-sm leading-relaxed shadow-sm ${
                          msg.sender === 'user' 
                            ? 'bg-primary text-white rounded-tr-none' 
                            : 'bg-white/5 text-slate-200 border border-white/5 rounded-tl-none'
                        }`}>
                          {msg.text}
                        </div>
                        <span className="text-[9px] font-bold text-slate-500 mt-1.5 uppercase tracking-tighter">{msg.time}</span>
                      </div>
                    ))}
                  </div>
                </ScrollArea>
                <form onSubmit={handleSendMessage} className="p-4 bg-slate-950/50 border-t border-white/5 flex gap-2">
                  <Input 
                    placeholder="Type a message..." 
                    className="bg-white/5 border-white/10 text-white text-xs h-10 rounded-xl focus-visible:ring-primary/50"
                    value={newMessage}
                    onChange={(e) => setNewMessage(e.target.value)}
                  />
                  <Button type="submit" size="icon" className="h-10 w-10 shrink-0 hero-gradient rounded-xl shadow-lg shadow-primary/20">
                    <Send className="h-4 w-4" />
                  </Button>
                </form>
              </TabsContent>

              <TabsContent value="prescription" className="flex-1 p-6 m-0 overflow-y-auto">
                {showPrescription ? (
                  <div className="space-y-6 animate-fade-in">
                    <div className="rounded-2xl bg-white p-6 text-slate-900 shadow-2xl relative overflow-hidden">
                      <div className="absolute top-0 right-0 w-24 h-24 bg-primary/5 rounded-full -mr-12 -mt-12" />
                      
                      <div className="flex justify-between items-start border-b border-slate-100 pb-4 mb-4 relative z-10">
                        <div>
                          <h3 className="font-extrabold text-sm text-primary">{doctor.name}</h3>
                          <p className="text-[9px] text-slate-500 font-bold uppercase tracking-wider">{doctor.specialty}</p>
                        </div>
                        <div className="text-right">
                          <p className="text-[9px] font-black text-slate-400 uppercase">Date</p>
                          <p className="text-[10px] font-bold">{new Date().toLocaleDateString()}</p>
                        </div>
                      </div>
                      
                      <div className="space-y-4 relative z-10">
                        <div className="flex items-center gap-2">
                          <div className="h-5 w-5 rounded-lg bg-primary/10 flex items-center justify-center text-primary text-[10px] font-black">Rx</div>
                          <p className="text-[10px] font-black uppercase tracking-widest text-slate-400">Prescription</p>
                        </div>
                        
                        <div className="space-y-3">
                          <div className="p-3 rounded-xl bg-slate-50 border border-slate-100 group hover:border-primary/20 transition-colors">
                            <p className="text-[11px] font-bold text-slate-800">Paracetamol 500mg</p>
                            <p className="text-[9px] text-slate-500 mt-1">1 tablet twice daily after meals (3 days)</p>
                          </div>
                          <div className="p-3 rounded-xl bg-slate-50 border border-slate-100 group hover:border-primary/20 transition-colors">
                            <p className="text-[11px] font-bold text-slate-800">Vitamin C 500mg</p>
                            <p className="text-[9px] text-slate-500 mt-1">1 tablet daily (10 days)</p>
                          </div>
                        </div>
                      </div>

                      <div className="mt-6 pt-4 border-t border-slate-100 flex justify-between items-center relative z-10">
                        <div className="flex flex-col gap-1">
                          <div className="h-10 w-24 bg-slate-50 rounded border border-slate-100 flex items-center justify-center">
                            <div className="h-6 w-20 border-b border-slate-300 border-dashed" />
                          </div>
                          <p className="text-[8px] font-bold text-slate-400 uppercase tracking-tighter">Digital Signature</p>
                        </div>
                        <div className="text-right">
                          <Badge variant="outline" className="text-[8px] border-success/30 text-success bg-success/5 font-black">VERIFIED</Badge>
                        </div>
                      </div>
                    </div>

                    <div className="grid grid-cols-2 gap-3">
                      <Button variant="outline" size="sm" className="text-[10px] h-10 gap-2 border-white/10 bg-white/5 hover:bg-white/10 rounded-xl font-bold">
                        <Download className="h-3.5 w-3.5" /> Download
                      </Button>
                      <Button size="sm" className="text-[10px] h-10 gap-2 hero-gradient rounded-xl font-bold shadow-lg shadow-primary/20" onClick={() => {
                        toast.success("Medicines added to cart!");
                        navigate("/medicines");
                      }}>
                        <ShoppingCart className="h-3.5 w-3.5" /> Order Now
                      </Button>
                    </div>
                  </div>
                ) : (
                  <div className="flex flex-col items-center justify-center h-full text-center py-12 opacity-40">
                    <div className="h-16 w-16 rounded-full bg-white/5 flex items-center justify-center mb-4">
                      <FileText className="h-8 w-8 text-slate-500" />
                    </div>
                    <p className="text-xs font-bold text-slate-500 uppercase tracking-widest">No prescription yet</p>
                    <p className="text-[10px] text-slate-600 mt-2 max-w-[200px]">The doctor will generate an e-prescription during the call if required.</p>
                  </div>
                )}
              </TabsContent>
            </Tabs>
          </div>
        )}
      </div>
      
      <style dangerouslySetInnerHTML={{ __html: `
        .mirror {
          transform: scaleX(-1);
        }
        @keyframes pulse-gentle {
          0%, 100% { transform: scale(1); opacity: 1; }
          50% { transform: scale(1.05); opacity: 0.9; }
        }
        .animate-pulse-gentle {
          animation: pulse-gentle 2s ease-in-out infinite;
        }
      `}} />
    </div>
  );
};

export default VideoCall;