"use client";

import React, { useState, useEffect, useRef } from "react";
import { useParams, useLocation, useNavigate } from "react-router-dom";
import { 
  Mic, MicOff, Video, VideoOff, PhoneOff, 
  MessageSquare, FileText, Send, X, 
  Maximize2, Settings, User, Download, ShoppingCart
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { toast } from "sonner";

const VideoCall = () => {
  const { appointmentId } = useParams();
  const location = useLocation();
  const navigate = useNavigate();
  const doctor = location.state?.doctor || { name: "Dr. Sarah Johnson", specialty: "General Physician", photoUrl: "https://images.unsplash.com/photo-1559839734-2b71f1536780?auto=format&fit=crop&q=80&w=200&h=200" };

  const [isMuted, setIsMuted] = useState(false);
  const [isVideoOff, setIsVideoOff] = useState(false);
  const [showChat, setShowChat] = useState(false);
  const [messages, setMessages] = useState([
    { id: 1, sender: "doctor", text: "Hello! How are you feeling today?", time: "10:00 AM" }
  ]);
  const [newMessage, setNewMessage] = useState("");
  const [callDuration, setCallDuration] = useState(0);
  const [showPrescription, setShowPrescription] = useState(false);

  useEffect(() => {
    const timer = setInterval(() => {
      setCallDuration(prev => prev + 1);
    }, 1000);
    return () => clearInterval(timer);
  }, []);

  const formatTime = (seconds: number) => {
    const mins = Math.floor(seconds / 60);
    const secs = seconds % 60;
    return `${mins.toString().padStart(2, '0')}:${secs.toString().padStart(2, '0')}`;
  };

  const handleSendMessage = (e: React.FormEvent) => {
    e.preventDefault();
    if (!newMessage.trim()) return;
    
    const msg = {
      id: Date.now(),
      sender: "user",
      text: newMessage,
      time: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
    };
    
    setMessages([...messages, msg]);
    setNewMessage("");
    
    // Simulate doctor reply
    setTimeout(() => {
      if (newMessage.toLowerCase().includes("fever")) {
        setMessages(prev => [...prev, {
          id: Date.now() + 1,
          sender: "doctor",
          text: "I see. I'll prepare a prescription for the fever. Please take rest.",
          time: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
        }]);
        
        // Simulate prescription generation
        setTimeout(() => {
          setShowPrescription(true);
          toast.success("E-Prescription generated by doctor!");
        }, 2000);
      }
    }, 1500);
  };

  const handleEndCall = () => {
    toast.info("Consultation ended.");
    navigate("/teleconsultation");
  };

  return (
    <div className="flex h-screen flex-col bg-slate-950 text-white overflow-hidden">
      {/* Header */}
      <header className="flex items-center justify-between px-6 py-4 bg-slate-900/50 backdrop-blur-md border-b border-white/10">
        <div className="flex items-center gap-4">
          <div className="h-10 w-10 rounded-full overflow-hidden border border-primary/50">
            <img src={doctor.photoUrl} className="h-full w-full object-cover" />
          </div>
          <div>
            <h2 className="font-bold text-sm">{doctor.name}</h2>
            <p className="text-[10px] text-slate-400 uppercase tracking-wider">{doctor.specialty}</p>
          </div>
          <Badge variant="outline" className="ml-4 border-primary/30 text-primary bg-primary/5">
            {formatTime(callDuration)}
          </Badge>
        </div>
        
        <div className="flex items-center gap-2">
          <Button variant="ghost" size="icon" className="text-slate-400 hover:text-white">
            <Settings className="h-5 w-5" />
          </Button>
          <Button variant="ghost" size="icon" className="text-slate-400 hover:text-white">
            <Maximize2 className="h-5 w-5" />
          </Button>
        </div>
      </header>

      {/* Main Content */}
      <div className="flex flex-1 relative overflow-hidden">
        {/* Video Area */}
        <div className="flex-1 relative bg-slate-900 flex items-center justify-center">
          {/* Doctor Video (Main) */}
          <div className="absolute inset-0 flex items-center justify-center">
            <img 
              src="https://images.unsplash.com/photo-1559839734-2b71f1536780?auto=format&fit=crop&q=80&w=1200" 
              className="h-full w-full object-cover opacity-80"
              alt="Doctor Video"
            />
            <div className="absolute inset-0 bg-gradient-to-t from-slate-950/60 to-transparent" />
          </div>

          {/* User Video (PIP) */}
          <div className="absolute top-6 right-6 w-48 h-32 rounded-xl overflow-hidden border-2 border-white/20 shadow-2xl bg-slate-800 z-10">
            {isVideoOff ? (
              <div className="h-full w-full flex items-center justify-center bg-slate-800">
                <User className="h-10 w-10 text-slate-600" />
              </div>
            ) : (
              <div className="h-full w-full bg-slate-700 flex items-center justify-center">
                <p className="text-[10px] text-slate-400">Your Camera</p>
              </div>
            )}
            <div className="absolute bottom-2 left-2">
              <Badge className="bg-black/50 text-[8px] px-1">You</Badge>
            </div>
          </div>

          {/* Controls Overlay */}
          <div className="absolute bottom-8 left-1/2 -translate-x-1/2 flex items-center gap-4 z-20">
            <Button 
              variant={isMuted ? "destructive" : "secondary"} 
              size="icon" 
              className="h-12 w-12 rounded-full shadow-xl"
              onClick={() => setIsMuted(!isMuted)}
            >
              {isMuted ? <MicOff className="h-5 w-5" /> : <Mic className="h-5 w-5" />}
            </Button>
            
            <Button 
              variant={isVideoOff ? "destructive" : "secondary"} 
              size="icon" 
              className="h-12 w-12 rounded-full shadow-xl"
              onClick={() => setIsVideoOff(!isVideoOff)}
            >
              {isVideoOff ? <VideoOff className="h-5 w-5" /> : <Video className="h-5 w-5" />}
            </Button>

            <Button 
              variant="destructive" 
              size="icon" 
              className="h-14 w-14 rounded-full shadow-xl animate-pulse"
              onClick={handleEndCall}
            >
              <PhoneOff className="h-6 w-6" />
            </Button>

            <Button 
              variant={showChat ? "primary" : "secondary"} 
              size="icon" 
              className={`h-12 w-12 rounded-full shadow-xl ${showChat ? 'bg-primary' : ''}`}
              onClick={() => setShowChat(!showChat)}
            >
              <MessageSquare className="h-5 w-5" />
            </Button>

            <Button 
              variant="secondary" 
              size="icon" 
              className="h-12 w-12 rounded-full shadow-xl"
              onClick={() => setShowPrescription(!showPrescription)}
            >
              <FileText className="h-5 w-5" />
            </Button>
          </div>
        </div>

        {/* Sidebar (Chat / Prescription) */}
        {(showChat || showPrescription) && (
          <div className="w-80 bg-slate-900 border-l border-white/10 flex flex-col animate-slide-in">
            <Tabs defaultValue={showPrescription ? "prescription" : "chat"} className="flex-1 flex flex-col">
              <div className="px-4 pt-4">
                <TabsList className="grid w-full grid-cols-2 bg-slate-800">
                  <TabsTrigger value="chat">Chat</TabsTrigger>
                  <TabsTrigger value="prescription">E-Rx</TabsTrigger>
                </TabsList>
              </div>

              <TabsContent value="chat" className="flex-1 flex flex-col p-0 m-0">
                <ScrollArea className="flex-1 p-4">
                  <div className="space-y-4">
                    {messages.map(msg => (
                      <div key={msg.id} className={`flex flex-col ${msg.sender === 'user' ? 'items-end' : 'items-start'}`}>
                        <div className={`max-w-[80%] rounded-2xl px-3 py-2 text-sm ${
                          msg.sender === 'user' ? 'bg-primary text-white rounded-tr-none' : 'bg-slate-800 text-slate-200 rounded-tl-none'
                        }`}>
                          {msg.text}
                        </div>
                        <span className="text-[10px] text-slate-500 mt-1">{msg.time}</span>
                      </div>
                    ))}
                  </div>
                </ScrollArea>
                <form onSubmit={handleSendMessage} className="p-4 border-t border-white/10 flex gap-2">
                  <Input 
                    placeholder="Type message..." 
                    className="bg-slate-800 border-none text-white text-xs h-9"
                    value={newMessage}
                    onChange={(e) => setNewMessage(e.target.value)}
                  />
                  <Button type="submit" size="icon" className="h-9 w-9 shrink-0 hero-gradient">
                    <Send className="h-4 w-4" />
                  </Button>
                </form>
              </TabsContent>

              <TabsContent value="prescription" className="flex-1 p-4 m-0">
                {showPrescription ? (
                  <div className="space-y-4 animate-fade-in">
                    <div className="rounded-xl bg-white p-4 text-slate-900 shadow-lg">
                      <div className="flex justify-between items-start border-b pb-2 mb-3">
                        <div>
                          <h3 className="font-bold text-xs">{doctor.name}</h3>
                          <p className="text-[8px] text-slate-500 uppercase">{doctor.specialty}</p>
                        </div>
                        <div className="text-right">
                          <p className="text-[8px] font-bold">DATE</p>
                          <p className="text-[8px]">{new Date().toLocaleDateString()}</p>
                        </div>
                      </div>
                      
                      <div className="space-y-3">
                        <div className="flex items-center gap-2">
                          <div className="h-4 w-4 rounded bg-primary/10 flex items-center justify-center text-primary text-[10px] font-bold">Rx</div>
                          <p className="text-[10px] font-bold">Prescription</p>
                        </div>
                        
                        <div className="space-y-2">
                          <div className="p-2 rounded bg-slate-50 border border-slate-100">
                            <p className="text-[10px] font-bold">Paracetamol 500mg</p>
                            <p className="text-[8px] text-slate-500">1 tablet twice daily after meals (3 days)</p>
                          </div>
                          <div className="p-2 rounded bg-slate-50 border border-slate-100">
                            <p className="text-[10px] font-bold">Vitamin C 500mg</p>
                            <p className="text-[8px] text-slate-500">1 tablet daily (10 days)</p>
                          </div>
                        </div>
                      </div>

                      <div className="mt-4 pt-2 border-t flex justify-between items-center">
                        <div className="h-8 w-8 bg-slate-100 rounded flex items-center justify-center">
                          <div className="h-6 w-6 border border-slate-300 border-dashed" />
                        </div>
                        <p className="text-[8px] italic text-slate-400">Digitally Signed</p>
                      </div>
                    </div>

                    <div className="grid grid-cols-2 gap-2">
                      <Button variant="outline" size="sm" className="text-[10px] h-8 gap-1 border-white/10 bg-white/5 hover:bg-white/10">
                        <Download className="h-3 w-3" /> Download
                      </Button>
                      <Button size="sm" className="text-[10px] h-8 gap-1 hero-gradient" onClick={() => {
                        toast.success("Medicines added to cart!");
                        navigate("/medicines");
                      }}>
                        <ShoppingCart className="h-3 w-3" /> Order Now
                      </Button>
                    </div>
                  </div>
                ) : (
                  <div className="flex flex-col items-center justify-center h-full text-center py-12">
                    <FileText className="h-12 w-12 text-slate-700 mb-4" />
                    <p className="text-xs text-slate-500">No prescription generated yet.</p>
                  </div>
                )}
              </TabsContent>
            </Tabs>
          </div>
        )}
      </div>
    </div>
  );
};

export default VideoCall;